name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests with SurrealDB
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
      # Setup SurrealDB
      - name: Start SurrealDB
        uses: surrealdb/setup-surreal@v2
        with:
          surrealdb_version: latest
          surrealdb_port: 8000
          surrealdb_username: root
          surrealdb_password: root
          surrealdb_auth: false
          surrealdb_strict: false
          surrealdb_log: info
          surrealdb_additional_args: --allow-all
          surrealdb_retry_count: 30
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Wait for SurrealDB
      - name: Wait for SurrealDB
        run: |
          echo "Waiting for SurrealDB to become healthy..."
          until curl --fail http://localhost:8000/status; do
            echo "Waiting for SurrealDB..."
            sleep 1
          done
          echo "SurrealDB is up and running!"

      # Run tests
      - name: Run tests
        run: bun test

      # Stop SurrealDB and cleanup
      - name: Stop SurrealDB
        if: always()
        run: echo "Cleaning up... SurrealDB service will stop automatically."
